% Tue 17 Oct 09:39:29 CEST 2023
% Karl Kästner, Berlin
%
%  This program is free software: you can redistribute it and/or modify
%  it under the terms of the GNU General Public License as published by
%  the Free Software Foundation, either version 3 of the License, or
%  (at your option) any later version.
%
%  This program is distributed in the hope that it will be useful,
%  but WITHOUT ANY WARRANTY; without even the implied warranty of
%  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%  GNU General Public License for more details.
%
%  You should have received a copy of the GNU General Public License
%  along with this program.  If not, see <https://www.gnu.org/licenses/>.
%
% template class for Reaction-Advection-Diffusion models
classdef RAD_Model < handle
	properties
		% number of grid points
		nx
		% number of variables
		nvar
		% side length of computational domain
		L
		% duration of model run
		T = [0,1];
		% physical parameters of the model
		p   = struct('ex', [], ...
			     'ey', [], ...
			     'vx', [], ...
			     'vy', []);
		% mean of physical paramters
		pmu = struct();
		% spatial standard deviation of parameters
		pss = struct();
		% distribution and correlation of spatial noise
		psdist = struct();
		% spatial correlation length of parameters
		psl = struct();
		% standard deviation of temporal additive noise
		pts = struct();
		% standard deviation of temporal multiplicative noise
		ptsrel = struct();

		% covariance matrix of spatial heterogeneity
		psC;

		% spectral density of spatial heterogeneity
		psS;

		% boundary condition
		boundary_condition = {'circular','circular'; 'circular','circular'};

		% initial condition function or selection
		initial_condition

		% initial condition, values
		z0	

		% options
		opt = struct(  'heterogeneity_integration_order', 5 ...
			     , 'heterogeneity_oversampling_factor_spectral', 3 ...
			     , 'heterogeneity_p_window', 1 ...
			     , 'loadfinal', true ...
			     , 'load_existing', true ...
		             , 'rng', [] ...
			     , 'compute_class', @single ...
			     , 'time_integration', struct( 'scheme', 'trapezoidal' ...
			     				  , 'max_attempts', 10 ...
			     				  , 'adapt_step_length', true ...
							  , 'abstol', 1e-4 ...
			                                  , 'reltol', 1e-3 ...
			     				  , 'dt_initial', 1 ...
		             				  , 'dt_min', 0 ...
		             				  , 'dt_max', inf ...
						 	  , 'dt_event', inf ...
			                                  , 'dt_max_scale_up', sqrt(2) ...
			                                  , 'dt_min_scale_down', 0 ...
			     				  , 'dt_safety_factor', 0.8 ...
							  , 'dt_max_prec_scale', 2.5 ...
			     				  ... % , 'step_control_method', 'local' ...
						   ) ...
			     , 'nlsolver', struct(  'name', 'gauss-newton' ...
					          , 'maxiter', 10 ...
					          , 'abstol', 1e-3 ...
			     			  , 'line_search_maxiter', 20 ...
			     			  , 'line_search_ispos', 1 ...
					   ) ...
			     ... %, 'inner_m', 10 ...
			     ... %, 'inner2_maxiter_', inf ...
			     , 'linear_solver', struct(   'name', 'bicgstabl' ...
			     				, 'maxiter', 1e3 ...
						        , 'tol', sqrt(eps) ...
							, 'restart', inf ...
			     				, 'equilibrate', 0 ...
			     				, 'preconditioner', 'ilu' ...
						) ...
			     , 'solver',        'solve_step' ...
			     , 'time_stepper',  'step_split' ...
			     ... % , 'extrapolation_order', 0 ...
			     , 'stoch', false ...
			     , 'rms_delta_zo_rel_max', inf ...
			     ... % output options
			     , output = struct('dt',  inf ...
			 		     , 'class', @half ...
					     , 'store_step', false ...
					     , 'store_fluxes', false ...
					     , 'store_state_at_event', false ...
					     , 'path_str', './' ...
					     , 'base_str', 'rad-' ...
					      ) ...
			     );

		% solver options
		%odeopt

		% fields to be used to create unique model hash
		hashfield_C  = {  'L' ...
				, 'dx' ...
				, 'T' ...
				, 'pmu' ...
				, 'pss' ...
				, 'psl' ...
				, 'psdist' ...
				, 'pts' ...
				, 'ptsrel' ...
				, 'initial_condition' ...
				, 'boundary_condition' ...
				, 'opt.time_integration.scheme' ...
				, 'opt.time_integration.dt_initial' ...
				, 'opt.time_integration.abstol' ...
				, 'opt.time_integration.reltol' ...
				, 'opt.rms_delta_zo_rel_max' ...
				, 'opt.rng' ...
				, 'opt.solver' ...
				, 'opt.output.dt' ...
				, 'opt.output.class' ...
				, 'opt.heterogeneity_integration_order' ...
			        , 'opt.heterogeneity_oversampling_factor_spectral' ...
			        , 'opt.heterogeneity_p_window' ...
				}; % hashfield_C

		% stores model autput
		out = struct('zo', [],'to',[],'z_final',[],'runtime',[]);

		% stores temporary variables
		aux = struct();
	end
	methods
		function obj = RAD_Model(varargin)
			if (~isempty(varargin) && isstruct(varargin{1}))
				obj = copyfields_deep(varargin{1},obj);
			else
			    for idx=1:2:length(varargin)-1
				obj = setfield_deep(obj,varargin{idx},varargin{idx+1});
			    end
			end
		end
		function s = sigma(obj,t,z)
			s = [];
		end
		function [x,y] = x(obj,id)
			if (nargin()<2)
				id = 1;
			end
			% at cell centres
			x = ((0:obj.nx(id)-1)+0.5)*obj.L(id)/obj.nx(id);
			if (nargout()>1)
				y =  ((0:obj.nx(2)-1)+0.5)*obj.L(2)/obj.nx(2);
			end
			%if (length(obj.nx)>1)
			%	y = (0:obj.nx(2)-1)*obj.L(2)/obj.nx(2);
			%end
		end
		function [fx,fy,frr] = fourier_axis(obj)
			if (obj.ndim == 1)
				fx = fourier_axis(obj.L,obj.nx);
			else
				[fx,fy,frr] = fourier_axis_2d(obj.L,obj.nx);
			end
		end
		function ndim = ndim(obj)
			ndim = length(obj.nx);
		end
		function flag = advance_to_next_event(obj,t,z)
			flag = false;
		end
	end
end

