% Thu 11 Jun 19:03:05 CEST 2026
classdef Tlidi < RAD_Model
properties
end % properties
	
methods
	function obj = Tlidi_(obj)
		obj.nvar = 1;	  % model is univariate in biomass	
		% mean of model parameters
		obj.pmu = struct( ...
		  'bc',   NaN ... % upper bimoass in logistic function
		, 'dirc', NaN ... % displacement of competition kernel
		, 'dirf', NaN ... % displacement of facilitation kernel
		, 'ef',   NaN ... % scale of facilitation (growth rate)
		, 'ex',   {{NaN}} ... % biomass diffusion along first axis
		, 'ey',   {{NaN}} ... % biomass diffusion along second axix
		, 'lc',   NaN ... % extent of competition kernel
		, 'lf',   NaN ... % extent of facilitation kernel
		, 'mu',   NaN ... % scale of competition (biomass dieback rate)
		, 'xc',   NaN ... % exponent of competition 
		, 'xf',   NaN ... % exponent of facilitation
		, 'vx',    {{0}} ...
		, 'vy',    {{0}} ...
		);
		% spatial variance of model parameters
		obj.pss = struct( ...
		  'bc',   0 ...
		, 'dirc', 0 ...
		, 'dirf', 0 ...
		, 'ef',   0 ...
		, 'ex',   0 ...
		, 'ey',   0 ...
		, 'lc',   0 ...
		, 'lf',   0 ...
		, 'mu',   0 ...
		, 'xc',   0 ...
		, 'xf',   0 ...
		, 'vx',   0 ...
		, 'vy',   0 ...
		... , 'ls', 0 ...
		);
		% spatial correlation lenght of random component
		obj.psl = struct( ...
				   'bc', 0 ...
				 , 'dirc', 0 ...
				 , 'dirf', 0 ...
				 , 'ef', 0 ...
				 , 'ex', 0 ...
				 , 'ey', 0 ...
				 , 'lc',   0 ...
				 , 'lf',   0 ...
				 , 'mu', 0 ...
				 , 'xc', 0 ...
			 	 , 'xf', 0 ...
		                 , 'vx', [] ...
		                 , 'vy', [] ...
				 );
		obj.psdist = struct( ...
				   'bc', 'lognormal' ...
				 , 'dirc', [] ...
				 , 'dirf', [] ...
				 , 'ef', 'lognormal' ...
				 , 'ex', 'lognormal' ...
				 , 'ey', 'lognormal' ...
				 , 'lc',   [] ...
				 , 'lf',   [] ...
				 , 'mu', 'lognormal' ...
				 , 'xc', 'normal' ...
			 	 , 'xf', 'normal' ...
		                 , 'vx', [] ...
		                 , 'vy', [] ...
				 );
		obj.opt.p_initial = 0.01;
		obj.opt.output.base_str  = 'tlidi';
	end % properties 

	function obj = Tlidi(varargin)
		obj = obj.Tlidi_();
		if (~isempty(varargin) && isstruct(varargin{1}))
			obj = copyfields_deep(varargin{1},obj);
		else
		    for idx=1:2:length(varargin)-1
			obj = setfield_deep(obj,varargin{idx},varargin{idx+1});
		    end
		end
	end % constructor
end % methods

end % classdef Tlidi

