% Tue 24 Oct 09:48:16 CEST 2023
% Karl Kästner, Berlin
%
%  This program is free software: you can redistribute it and/or modify
%  it under the terms of the GNU General Public License as published by
%  the Free Software Foundation, either version 3 of the License, or
%  (at your option) any later version.
%
%  This program is distributed in the hope that it will be useful,
%  but WITHOUT ANY WARRANTY; without even the implied warranty of
%  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%  GNU General Public License for more details.
%
%  You should have received a copy of the GNU General Public License
%  along with this program.  If not, see <https://www.gnu.org/licenses/>.
function z0 = homogeneous_state(obj,t,p)
	if (nargin()<3)
		p = obj.pmu;
	end
	a = p.a;
	b = p.b;
	ze = p.ze;
	zmax = p.zmax;
	l0 = p.l0;
	w0 = p.w0;


      z0 = [((a.*b.*ze - a.*l0 + a.*b.*zmax).^2./(9.*a.^2.*b.^2) + (a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax)./(3.*a.*b))./((((a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^2 - ((a.*b.*ze - a.*l0 + a.*b.*zmax).^2./(9.*a.^2.*b.^2) + (a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax)./(3.*a.*b)).^3).^(1./2) + (a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^(1./3) + ((((a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^2 - ((a.*b.*ze - a.*l0 + a.*b.*zmax).^2./(9.*a.^2.*b.^2) + (a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax)./(3.*a.*b)).^3).^(1./2) + (a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^(1./3) + (a.*b.*ze - a.*l0 + a.*b.*zmax)./(3.*a.*b) ...
, (a.*b.*ze - a.*l0 + a.*b.*zmax)./(3.*a.*b) - (3.^(1./2).*(((a.*b.*ze - a.*l0 + a.*b.*zmax).^2./(9.*a.^2.*b.^2) + (a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax)./(3.*a.*b))./((((a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^2 - ((a.*b.*ze - a.*l0 + a.*b.*zmax).^2./(9.*a.^2.*b.^2) + (a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax)./(3.*a.*b)).^3).^(1./2) + (a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^(1./3) - ((((a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^2 - ((a.*b.*ze - a.*l0 + a.*b.*zmax).^2./(9.*a.^2.*b.^2) + (a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax)./(3.*a.*b)).^3).^(1./2) + (a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^(1./3)).*1i)./2 - ((((a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^2 - ((a.*b.*ze - a.*l0 + a.*b.*zmax).^2./(9.*a.^2.*b.^2) + (a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax)./(3.*a.*b)).^3).^(1./2) + (a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^(1./3)./2 - ((a.*b.*ze - a.*l0 + a.*b.*zmax).^2./(9.*a.^2.*b.^2) + (a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax)./(3.*a.*b))./(2.*((((a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^2 - ((a.*b.*ze - a.*l0 + a.*b.*zmax).^2./(9.*a.^2.*b.^2) + (a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax)./(3.*a.*b)).^3).^(1./2) + (a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^(1./3)) ...
, (a.*b.*ze - a.*l0 + a.*b.*zmax)./(3.*a.*b) + (3.^(1./2).*(((a.*b.*ze - a.*l0 + a.*b.*zmax).^2./(9.*a.^2.*b.^2) + (a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax)./(3.*a.*b))./((((a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^2 - ((a.*b.*ze - a.*l0 + a.*b.*zmax).^2./(9.*a.^2.*b.^2) + (a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax)./(3.*a.*b)).^3).^(1./2) + (a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^(1./3) - ((((a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^2 - ((a.*b.*ze - a.*l0 + a.*b.*zmax).^2./(9.*a.^2.*b.^2) + (a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax)./(3.*a.*b)).^3).^(1./2) + (a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^(1./3)).*1i)./2 - ((((a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^2 - ((a.*b.*ze - a.*l0 + a.*b.*zmax).^2./(9.*a.^2.*b.^2) + (a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax)./(3.*a.*b)).^3).^(1./2) + (a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^(1./3)./2 - ((a.*b.*ze - a.*l0 + a.*b.*zmax).^2./(9.*a.^2.*b.^2) + (a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax)./(3.*a.*b))./(2.*((((a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^2 - ((a.*b.*ze - a.*l0 + a.*b.*zmax).^2./(9.*a.^2.*b.^2) + (a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax)./(3.*a.*b)).^3).^(1./2) + (a.*b.*ze - a.*l0 + a.*b.*zmax).^3./(27.*a.^3.*b.^3) - (w0 + a.*l0.*ze.*zmax)./(2.*a.*b) + ((a.*l0.*ze + a.*l0.*zmax - a.*b.*ze.*zmax).*(a.*b.*ze - a.*l0 + a.*b.*zmax))./(6.*a.^2.*b.^2)).^(1./3))];

end

